version: "3"

services:
  redis:
    image: redis:3.2.9
    ports:
    - 6379:6379
    volumes:
    - "/docker/redis/conf/redis.conf:/etc/redis/redis.conf"
    - "/docker/redis/data:/data"
    networks:
      - my_app_net
    restart: always
#    command: redis-server
    container_name: redis
    privileged: true
  db:
    image: mysql:8.0.33
    ports:
    - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root
    volumes:
    - "/docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf"
    - "/docker/mysql/logs:/var/log/mysql"
    - "/docker/mysql/data:/var/lib/mysql"
    - "/docker/mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    - "/etc/localtime:/etc/localtime"
    networks:
      - my_app_net
    restart: always
#    command: --init-file /docker-entrypoint-initdb.d/init.sql
    container_name: mysql
    privileged: true
  my-app:
    image: my-app:v1
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
    - 9000:9000
    networks:
      - my_app_net
    depends_on:
      - mysql
      - redis
    restart: always
    container_name: my-app
    privileged: true
networks:
  my_app_net:
    driver: bridge

