spring:
  application:
    name: simple-java-maven-app
  config:
    import:
      - classpath:application-mvc.yml
      - classpath:application-shardingsphere.yml
      - classpath:application-mail.yml
      - classpath:application-jpa.yml
      - classpath:application-redis.yml
      - classpath:application-nacos.yml
      - classpath:application-xxljob.yml
app:
  security:
    disable: true
  jwt:
    prefix: "Bearer "
    ttl: 30 # minutes
    refreshTtl: 30 #minutes