spring:
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtps
    username: "13076894376@163.com"
    password: "NYxUx37Z5pkjeWtV"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true