### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    enabled: false
    admin.addresses: ${XXL_ADMIN_ADDRESS}
    accessToken: xxlaccess
    executor:
      appname: ${spring.application.name:simple-java-maven-app}
      address:
      ip: 192.168.0.102
      port: 13001
      logpath: ./xxl-job-logs
      logretentiondays: 30
